// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_cNuHN7Kg0i6L6qSFeEBPBsHvsU_ZXA0',
    appId: '1:1029733319658:web:05820a3be7a2c52a47e893',
    messagingSenderId: '1029733319658',
    projectId: 'fir-lessons-b65b2',
    authDomain: 'fir-lessons-b65b2.firebaseapp.com',
    storageBucket: 'fir-lessons-b65b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLGjn0AmIYjWTUWqMbagkecirj99ue5zA',
    appId: '1:1029733319658:android:90cb161fcf5b7e4047e893',
    messagingSenderId: '1029733319658',
    projectId: 'fir-lessons-b65b2',
    storageBucket: 'fir-lessons-b65b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbDWjMeL9KRXpYN31Y9QREr3ckS-tKivk',
    appId: '1:1029733319658:ios:cba4d464b95743f747e893',
    messagingSenderId: '1029733319658',
    projectId: 'fir-lessons-b65b2',
    storageBucket: 'fir-lessons-b65b2.appspot.com',
    iosClientId: '1029733319658-crlcrp4rlqs8qh063l63bea0o3923nlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleFirebase',
  );
}
